[View in Colaboratory](https://colab.research.google.com/github/anirbanghoshsbi/sklearn_tricks/blob/master/OHE_and_IE_sklearn.ipynb)

In [0]:
#import the libraries
import numpy as np
from sklearn.preprocessing import LabelEncoder # for integer encoding
from sklearn.preprocessing import LabelBinarizer # binary encoding

In [0]:
# categorical data
y = ['dog','car','sat','rat','tan','was']


In [0]:
# convert it to numpy array
y = np.array(y)

In [0]:
#integer encode it
le = LabelEncoder()
le.fit(y)

LabelEncoder()

In [0]:
# encode the labels
labels_int =  le.transform(y)


In [12]:
labels_int

array([1, 0, 3, 2, 4, 5])

In [0]:
# Binarize the data
lb = LabelBinarizer()
labels_bin = lb.fit_transform(labels_int)

In [14]:
labels_bin #  can pass the integer encoded data to the sklearn LabelBinarizer
# or we can also pass the raw data to the LabelBinarizer to get OHE.

array([[0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [0]:
label_bin = lb.fit_transform(y)

In [16]:
label_bin

array([[0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])